server:
  port: ${PORT:8082}
spring:
  application:
    name: imgify-server
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:imgify}?useSSL=true&requireSSL=true&verifyServerCertificate=false
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    hikari:
      initialization-fail-timeout: -1
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:5175}

clipdrop:
  api:
    key: bd1e34b73d5a9c43f2966a2a34a5fe66816e79abb0dd7700233a222c2ef367cce352aeec368f601082f2f2eef8d43e79
    url: https://clipdrop-api.co/text-to-image/v1
