server:
  port: 8082
spring:
  application:
    name: imgify-server
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/imgify}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

clipdrop:
  api:
    key: bd1e34b73d5a9c43f2966a2a34a5fe66816e79abb0dd7700233a222c2ef367cce352aeec368f601082f2f2eef8d43e79
    url: https://clipdrop-api.co/text-to-image/v1
